import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StrictMode } from "react";
import { App } from "@/App.tsx";
import * as ipc from "@/shared/ipc.ts";
import { AppProvider } from "@/shared/store.tsx";

export function renderApp({ strictMode = false }: { strictMode?: boolean } = {}) {
  const app = (
    <AppProvider>
      <App />
    </AppProvider>
  );
  return render(
    strictMode ? <StrictMode>{app}</StrictMode> : app,
  );
}

/** Replace a field value without paying for unrelated per-character rerenders. */
export async function fillText(
  user: ReturnType<typeof userEvent.setup>,
  field: Element,
  value: string,
) {
  await user.clear(field);
  await user.click(field);
  await user.paste(value);
}

/** Append setup text while preserving a workflow prompt already generated by the UI. */
export async function appendText(
  user: ReturnType<typeof userEvent.setup>,
  field: Element,
  value: string,
) {
  await user.click(field);
  await user.keyboard("{End}");
  await user.paste(value);
}

export async function openBundle(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getAllByRole("button", { name: /open folder/i })[0]);
  await screen.findByRole("button", { name: /switch bundle/i });
}

export const openFolder = openBundle;

export async function openAgentThread(name: string) {
  const profile = await ipc.saveCustomAgent({
    name,
    executable: `C:\\tools\\${name.toLowerCase().replaceAll(" ", "-")}.exe`,
    arguments: [],
    environment: [],
  });
  const connection = await ipc.connectCustomAgent(profile.id, "/mock/workspace/docs");
  const user = userEvent.setup();
  renderApp();
  await openFolder(user);
  await user.click(screen.getByRole("button", { name: /toggle agent panel/i }));
  await screen.findByRole("heading", { name: "New thread" });
  return { connection, profile, user };
}

export async function openBundleAtOverview(user: ReturnType<typeof userEvent.setup>) {
  await openBundle(user);
  await user.click(screen.getByRole("treeitem", { name: "Overview" }));
  await screen.findByRole("heading", { name: "Overview", level: 1 });
}

export async function openAttachmentMenu(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole("button", { name: "Add context or sources" }));
}

export async function openThreadActions(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole("button", { name: "More thread actions" }));
}

export async function chooseThreadAction(
  user: ReturnType<typeof userEvent.setup>,
  name: string,
) {
  await openThreadActions(user);
  await user.click(await screen.findByRole("menuitem", { name }));
}
