// The v0.2 trust panel across the states a real bundle produces. Each story is a
// decision a reader makes differently, not a variation on a theme.

import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, fn } from "storybook/test";
import { mockConcept } from "@/mock/conceptFixtures.ts";
import { ConceptTrust } from "./ConceptTrust.tsx";

// Pinned so a staleness story does not change verdict as the calendar moves.
const TODAY = "2026-07-27";

function Rail({ children }: { children: React.ReactNode }) {
  // Approximates the Reader's rail, which is where this renders and the width
  // that decides whether an actor string wraps sensibly.
  return (
    <div style={{ width: 320, padding: "var(--space-12)", background: "var(--bg-elev)" }}>
      {children}
    </div>
  );
}

const meta = {
  title: "Reader/ConceptTrust",
  component: ConceptTrust,
  // Supplied so the openable-source path renders; the Reader passes the
  // app's external opener here.
  args: { today: TODAY, onOpenResource: fn() },
  render: (args) => (
    <Rail>
      <ConceptTrust {...args} />
    </Rail>
  ),
} satisfies Meta<typeof ConceptTrust>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Generated by an agent and confirmed by nobody. The default state of new
 * knowledge, and deliberately quiet rather than alarming.
 */
export const Unverified: Story = {
  args: {
    concept: mockConcept({
      generated: { by: "reference_agent/gemini-2.5-pro", at: "2026-06-20T22:53:05Z" },
    }),
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText("Unverified")).toBeVisible();
    // Provenance is not confirmation, and the panel must not imply it is.
    await expect(canvas.getByText(/Treat it as generated, not reviewed/)).toBeVisible();
  },
};

/** A nightly process signed off; no human has looked. */
export const MachineConfirmed: Story = {
  args: {
    concept: mockConcept({
      generated: { by: "reference_agent/gemini-2.5-pro", at: "2026-06-20T22:53:05Z" },
      verified: [{ by: "process:finance-nightly", at: "2026-06-26T02:00:00Z" }],
    }),
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText("Machine-confirmed")).toBeVisible();
  },
};

/**
 * Both a process and a person. The human entry is what raises the tier, so it is
 * picked out of the list.
 */
export const HumanReviewedWithSources: Story = {
  args: {
    concept: mockConcept({
      generated: { by: "reference_agent/gemini-2.5-pro", at: "2026-06-20T22:53:05Z" },
      verified: [
        { by: "process:finance-nightly", at: "2026-06-26T02:00:00Z" },
        { by: "human:ahormati", at: "2026-06-25T09:00:00Z" },
      ],
      usageWindow: { from: "2026-06-01", to: "2026-06-30" },
      sources: [
        {
          resource: "https://wiki.example/finance/revenue-recognition",
          id: "rev-policy",
          title: "Revenue recognition policy",
          author: "human:ahormati",
          usageCount: 5000,
          lastModified: "2026-05-30",
        },
        // A population the reader cannot follow, which is a legitimate resource
        // and must not be rendered as a link.
        {
          resource: "all queries in BigQuery project acme-analytics",
          id: null,
          title: null,
          author: null,
          usageCount: null,
          lastModified: null,
        },
      ],
    }),
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText("Human-reviewed")).toBeVisible();
    await expect(canvas.getByText("Revenue recognition policy")).toBeVisible();
    await expect(
      canvas.getByText("all queries in BigQuery project acme-analytics"),
    ).toBeVisible();
    // A followable source gets a button, because an anchor would navigate the
    // webview away from the app.
    await expect(
      canvas.getByRole("button", { name: /wiki.example\/finance/ }),
    ).toBeVisible();
    // The scope descriptor is neither: nothing to open.
    await expect(
      canvas.queryByRole("button", { name: /all queries in BigQuery/ }),
    ).toBeNull();
  },
};

/** Past its staleness date: the reader should see that before anything else. */
export const Stale: Story = {
  args: {
    concept: mockConcept({
      staleAfter: "2026-05-01",
      verified: [{ by: "human:ahormati", at: "2026-01-25T09:00:00Z" }],
    }),
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText(/Stale since 2026-05-01/)).toBeVisible();
    // Staleness does not erase the review that happened; both are true.
    await expect(canvas.getByText("Human-reviewed")).toBeVisible();
  },
};

/**
 * Deprecated and stale. Deprecation wins the notice: it is not coming back,
 * where a stale concept may simply be awaiting review.
 */
export const Deprecated: Story = {
  args: {
    concept: mockConcept({
      status: "deprecated",
      staleAfter: "2026-05-01",
    }),
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText(/Deprecated/)).toBeVisible();
    await expect(canvas.queryByText(/Stale since/)).toBeNull();
  },
};

/** Not yet reviewed and possibly incomplete. */
export const Draft: Story = {
  args: { concept: mockConcept({ status: "draft" }) },
};

/**
 * A v0.1 concept declares none of this, and the panel renders nothing rather
 * than an empty well that would read as an accusation.
 */
export const NothingDeclared: Story = {
  args: { concept: mockConcept({ timestamp: "2026-01-15T10:00:00Z" }) },
  play: async ({ canvasElement }) => {
    await expect(canvasElement.querySelector(".concept-trust")).toBeNull();
  },
};

/** A long actor and a long source title, which is where the rail gives out. */
export const LongValues: Story = {
  args: {
    concept: mockConcept({
      generated: {
        by: "internal_platform_reference_agent/gemini-2.5-pro-preview-0827",
        at: "2026-06-20T22:53:05Z",
      },
      sources: [{
        resource:
          "https://wiki.example.internal/finance/policies/revenue-recognition-and-deferral-guidance-2026",
        id: "rev",
        title:
          "Revenue recognition and deferral guidance for the 2026 fiscal year, finance policy handbook",
        author: "process:finance-policy-sync",
        usageCount: 1234567,
        lastModified: "2026-05-30",
      }],
      usageWindow: { from: "2026-06-01", to: "2026-06-30" },
    }),
  },
};
